### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by dimrozakis** [zmap/celerybeat-mongo#27]
Hey there, do you think you could bump up the version and publish a new release to pypi?

Btw, the version in setup.py is 0.0.11 whereas version 0.1.0 is available on pypi.

**Comment by mdantonio** [comment]
Both pypi and setup.py versions are now 0.1.0 but pypi release is very outdated (11 Nov 2016) ... it is possible to update the package? (maybe by bumping a new version... 0.1.1; 0.2.0 or what you prefer)

Be able to install from pypi would be much easier than use the github link, in particular because pip has some difficulties to manage packages with dependencies provided as URLs (i'm using celerybeat-mongo as a dependency in my project)

**Comment by zakird** [comment]
Sure, Let's cut this when #42 is merged. It's close.

**Comment by mdantonio** [comment]
Thank very much

**Comment by quaxsze** [comment]
Hi, as it has been merged, It would be indeed nice to have a release :)
Thx!

**Comment by zakird** [comment]
agree! I'll try to get this out today.

**Comment by zakird** [comment]
I have tagged and released v0.2.0.
