### ISSUE TITLE
Interval and Crontab models as separated class

### ISSUE THREAD

**Issue by rafaelreuber** [zmap/celerybeat-mongo#48]
All celerybeat-mongo models are centralized on celerybeatmongo.models.PeriodicTask, having and Interval and Crontab as nested classes. I think it could be better to make Interval and Crontab as separated class. This can make  easy to maintain and to write unit test. 

Is not a good practice to make PeriodicTask as a "god class". The code could be messy over time when, for example, we add the Solar scheduler support.

**Comment by zakird** [comment]
We decided to do it this way because then you can have a single collection of scheduled tasks and interact with all tasks in a simple manner. The differences between Interval and Crontab are very small compared to the rest of the class being shared. Can you share a concrete problem this is causing today?

At this point, changing this would be a huge headache for everyone already relying on the project, and there isn't really any other code in the project. I don't mean to sound harsh here, but without a significant compelling reason, it sounds like we'd break a lot of folks setup without much benefit. 
 As such, it might make the most sense to fork the project if you want to change how the models are constructed, since we'd have to change the rest of the code to accommodate the change anyway.

**Comment by rafaelreuber** [comment]
You're right this change will not bring such benefits to worth the incompatibility.

**Comment by rafaelreuber** [comment]
But it's possible to this without break compatibility.

```python
class Crontab(EmbeddedDocument):  
    """Crontab-like schedule."""

class Interval(EmbeddedDocument):
    """Schedule executing on a regular interval."""

class PeriodicTask(DynamicDocument):
    """"MongoDB model that represents a periodic task""""

    class Interval(Interval):
        pass
    class Crontab(Crontab):
        pass
```

**Comment by zakird** [comment]
If you're able to submit a PR that fixes this and can provide tests that convincingly show that this does not break any existing users' stored schedules, I'm happy to look at. I don't think any of the core team though has the bandwidth to champion this though given that it's not posing any problems for us.

**Comment by rafaelreuber** [comment]
Nice! By the way would be nice have a development branch.

**Comment by zakird** [comment]
Master is considered mainline development. We will tag and release when appropriate.
